export const funFacts = [
  "PDFs were invented by Adobe in 1993 and originally cost $50 per copy!",
  "The average office worker prints 10,000 sheets of paper per year.",
  "Combining pages can reduce printing costs by up to 75%.",
  "The first PDF file ever created was about the Adobe Acrobat announcement.",
  "PDF stands for Portable Document Format - designed to look the same everywhere.",
  "Over 2.5 trillion PDF files exist on the internet today.",
  "The largest PDF file ever created was 1.4 GB - a digitized medieval manuscript.",
  "Grayscale printing uses 60% less ink than color printing.",
  "The average student prints over 1,000 pages per semester.",
  "PDF files can contain up to 200 inches × 200 inches pages (that's huge!).",
  "Inverting colors can make documents easier to read in dark environments.",
  "The PDF format supports over 14 different compression algorithms.",
  "Adobe Acrobat was originally called 'Carousel' during development.",
  "PDFs can be password protected with 256-bit AES encryption.",
  "The smallest valid PDF file is only 9 bytes long!",
  "PDF/A format is designed to preserve documents for 100+ years.",
  "You can fit about 4 standard pages on one A4 sheet comfortably.",
  "Digital documents save approximately 2.5 million trees annually.",
  "The PDF specification is over 750 pages long (ironically).",
  "Modern PDFs can contain 3D models, videos, and interactive forms.",
  "The Library of Congress has over 15 million PDF documents in its digital collection.",
  "PDF files use a coordinate system where (0,0) is at the bottom-left corner.",
  "The first PDF viewer was released for free in 1994 to encourage adoption.",
  "PDF compression can reduce file sizes by up to 90% without quality loss.",
  "Adobe Reader has been downloaded over 1 billion times worldwide.",
  "PDFs support 16.7 million colors through RGB and CMYK color spaces.",
  "The PDF format was made an open standard (ISO 32000) in 2008.",
  "Some PDFs contain hidden layers that can be toggled on and off.",
  "PDF forms can automatically calculate totals and perform complex validations.",
  "The world's oldest digitized book in PDF format dates back to 868 AD.",
  "PDF files can be digitally signed to verify authenticity and prevent tampering.",
  "Bookmarks in PDFs can create interactive navigation for large documents.",
  "PDF annotations support 23 different types including sticky notes and highlights.",
  "The PDF format supports transparency effects and blend modes like Photoshop.",
  "Some PDFs are designed to be accessible to screen readers for visually impaired users.",
  "PDF portfolios can combine multiple file types into a single container.",
  "The smallest font size supported in PDFs is 0.01 points (virtually invisible).",
  "PDF files can trigger JavaScript actions when opened or when buttons are clicked.",
  "Linearized PDFs are optimized for web viewing and load page-by-page.",
  "The PDF format supports both vector graphics and raster images seamlessly.",
  "PDF files can contain embedded fonts to ensure consistent appearance across devices.",
  "Some PDFs include geospatial data for mapping and GIS applications.",
  "The PDF/X standard is specifically designed for professional printing workflows.",
  "PDF files can be created from virtually any application that can print.",
  "Tagged PDFs include structural information that improves accessibility and reflow.",
  "The PDF format supports 40-bit, 128-bit, and 256-bit encryption levels.",
  "PDF files can contain multimedia elements like audio and video clips.",
  "Some PDFs use OCR (Optical Character Recognition) to make scanned text searchable.",
  "The PDF format supports custom metadata fields for document management systems.",
  "PDF files can be optimized for different purposes: web, print, or archival storage.",
  "Some PDFs contain embedded 3D models that can be rotated and manipulated.",
  "The PDF format supports both RGB (screen) and CMYK (print) color profiles.",
  "PDF files can include digital certificates for legal document validation.",
  "Some PDFs are designed to work offline with embedded databases and forms.",
  "The PDF format supports Unicode, allowing text in virtually any language.",
  "PDF files can contain hyperlinks that work both within the document and to external URLs.",
  "Some PDFs include embedded spreadsheets that retain full Excel functionality.",
  "The PDF format supports custom page sizes beyond standard paper dimensions.",
  "PDF files can be created with expiration dates for time-sensitive documents.",
  "Some PDFs contain embedded CAD drawings with precise technical specifications.",
  "The PDF format supports both lossy and lossless image compression algorithms.",
  "PDF files can include form fields that automatically sync with databases.",
  "Some PDFs are designed as interactive presentations with slide transitions.",
  "The PDF format supports watermarks that can be visible or invisible until printed.",
  "PDF files can contain embedded audio narration for accessibility purposes.",
  "Some PDFs include barcode generation for inventory and tracking systems.",
  "The PDF format supports custom color spaces for specialized printing needs.",
  "PDF files can be created with different security levels for different user groups.",
  "Some PDFs contain embedded weather data and real-time information feeds.",
  "The PDF format supports both horizontal and vertical text orientation.",
  "PDF files can include embedded calculators and interactive widgets.",
  "Some PDFs are designed to work as standalone applications with full interfaces.",
  "The PDF format supports advanced typography features like kerning and ligatures.",
  "PDF files can contain embedded maps with GPS coordinates and routing information.",
  "Some PDFs include real-time collaboration features for shared editing.",
  "The PDF format supports custom paper sizes for specialized printing equipment.",
  "PDF files can be created with automatic backup and version control systems.",
  "Some PDFs contain embedded databases that can be queried and filtered.",
  "The PDF format supports both static and dynamic content generation.",
  "PDF files can include embedded timers and countdown functionality.",
  "Some PDFs are designed as interactive catalogs with shopping cart functionality.",
  "The PDF format supports advanced security features like biometric authentication.",
  "PDF files can contain embedded weather widgets and live data feeds.",
  "Some PDFs include augmented reality markers for mobile app integration.",
  "The PDF format supports custom scripting languages for advanced automation.",
  "PDF files can be created with automatic translation capabilities for multiple languages."
]

export function getRandomFact(): string {
  return funFacts[Math.floor(Math.random() * funFacts.length)]
}