export const funFacts: string[] = [
  "About 44% of PDFs opened are just one page long, 90% are under 20 pages.",
  "Acrobat Preflight can validate PDF/A, PDF/X, and PDF/UA compliance automatically.",
  "Acrobat forms were originally called AcroForms after the Acrobat product name.",
  "Adobe Reader had 339 million unique desktop users reported in 2018.",
  "Alternate images allow different resolutions or soft masks for same image object.",
  "Annotation layers can separate comments from main content in some workflows.",
  "Annotations include text notes, highlights, ink marks, stamps, and links.",
  "Attached files can have icons displayed in Acrobat's attachments panel.",
  "Billions of PDF files are created every single day across the world.",
  "Bookmarks create a hierarchical table of contents for easy document navigation.",
  "Certificate-based encryption restricts PDF access to specific certificate holders.",
  "Certified PDFs include signatures indicating document has been checked and verified.",
  "Clipboard formats from PDFs include plain text, HTML, and images simultaneously.",
  "Color Management Systems use embedded ICC profiles to transform PDF colors.",
  "Composite CIDFonts enable Asian languages like Chinese, Japanese, and Korean.",
  "Compression ratios vary; text PDFs compress well while scanned images vary more.",
  "Content streams can be clipped to shapes, similar to CSS clipping paths.",
  "Copy-paste from PDF can yield gibberish without proper ToUnicode mapping table.",
  "Cross-reference streams since PDF 1.5 compress the xref table for smaller files.",
  "Digital signatures were added in PDF 1.3 to verify document authenticity.",
  "Early Acrobat Reader 1.0 was codenamed Carousel and could display basic PDFs.",
  "Email gateways often scan PDFs for malware, flagging JavaScript or launch actions.",
  "Embedded videos in PDFs typically require plugins and aren't widely supported.",
  "Error recovery scans from end for startxref or %%EOF if PDF structure damaged.",
  "Every PDF file has four parts: Header, Body, Cross-Reference Table, Trailer.",
  "Flattening converts annotations and form data into static page content.",
  "Flattening transparency converts blend objects to opaque art for older viewers.",
  "Form data can be exported as FDF or XFDF files for review workflows.",
  "Form flattening converts interactive fields to static content before printing.",
  "Fragmenting large PDFs into smaller files can improve loading and distribution.",
  "Full screen mode can launch automatically when PDF opens via OpenAction flag.",
  "GPU acceleration can speed up PDF rendering especially for images and graphics.",
  "Generation numbers in PDF objects theoretically allow multiple object revisions.",
  "Geospatial PDFs encode map coordinates and layers for GIS applications.",
  "Ghostscript is a free PostScript and PDF interpreter used by many PDF tools.",
  "Google Docs and LibreOffice can export to PDF without any additional software.",
  "Graphics state stack uses q/Q operators to save and restore transformations.",
  "Hyperlinks in PDF can point to URLs or named destinations within same document.",
  "Incremental updates append changes to PDF files without rewriting entire file.",
  "Ink annotations preserve pressure information from stylus or pen input.",
  "Interactive PDF ads can include click-through hyperlinks embedded in flyers.",
  "JavaScript can be embedded in PDFs for form calculations and interactions.",
  "Large PDFs can be split into volumes and merged later by copying objects.",
  "Layer printing intent lets authors specify layers only for print or only view.",
  "Linearization dictionary in first object tells viewer where to find page data.",
  "Linearized PDFs load the first page quickly, perfect for web viewing.",
  "Linux uses Poppler library and tools like Evince and Okular for PDF viewing.",
  "Maintaining integrity in PDF/A requires fonts to be fully embedded and licensed.",
  "Memory mapping can speed up large PDF viewing on tablets and mobile devices.",
  "Metadata can be stored in legacy Info dictionary or modern XMP XML streams.",
  "Microsoft Office since 2007 can export documents directly to PDF format natively.",
  "Mobile apps like Adobe Acrobat Reader are available free on iOS and Android.",
  "Modern browsers like Chrome, Edge, Firefox, and Safari have built-in PDF viewers.",
  "Multiple xref sections accumulate from incremental saves by different applications.",
  "Named actions on pages can trigger GoTo, Launch, or other behaviors automatically.",
  "Output intent profiles tell printers target color conditions for accurate output.",
  "Overprint and knockout settings control how colors blend in printing separations.",
  "PAdES extends PDF signatures for European qualified electronic signatures.",
  "PDF 1.2 introduced interactive forms called AcroForms with fields and buttons.",
  "PDF 1.4 introduced transparency and alpha blending to the imaging model.",
  "PDF 1.5 added layers called Optional Content Groups for toggling content.",
  "PDF 2.0 was published in 2020, removing all legacy proprietary features.",
  "PDF JavaScript is based on older ES3/ES5 and lacks some modern features.",
  "PDF allows alternate presentations feature for slideshow mode in Adobe Reader.",
  "PDF allows authors to hide menus and toolbars via viewer preferences dictionary.",
  "PDF allows defining MediaBox, CropBox, BleedBox, TrimBox, and ArtBox boundaries.",
  "PDF allows embedding entire font programs or just subset of used characters.",
  "PDF allows launching external files or applications via launch actions.",
  "PDF allows named destinations for bookmarks and links to specific page targets.",
  "PDF allows page transitions like dissolve and wipe for presentation mode.",
  "PDF allows specifying whether annotations print by default or remain on-screen.",
  "PDF allows storing custom XMP metadata schemas for industry-specific data.",
  "PDF allows storing private custom data in metadata using XMP namespaces.",
  "PDF became an open ISO standard in 2008 as ISO 32000-1, ending Adobe control.",
  "PDF can embed Type1, TrueType, and OpenType fonts to preserve exact text.",
  "PDF can embed any file type as attachments using the EmbeddedFiles entry.",
  "PDF can specify viewer preferences like hiding toolbars or fitting window size.",
  "PDF comments and markup are saved as annotation objects in the file structure.",
  "PDF documents are accepted for legal filings and e-signatures in many courts.",
  "PDF doesn't include file-level checksum; integrity checked via digital signatures.",
  "PDF doesn't natively hyphenate text; breaks occur only where explicitly forced.",
  "PDF doesn't support native animation with timelines or keyframes like video.",
  "PDF encryption is file-level; you cannot encrypt individual pages separately.",
  "PDF files can contain unique file ID in trailer for document fingerprinting.",
  "PDF files can specify default zoom level and page layout on document open.",
  "PDF files end with %%EOF marker to signify the end of the file structure.",
  "PDF is self-contained, embedding all fonts and data needed for rendering.",
  "PDF objects have generation numbers allowing multiple revisions in same file.",
  "PDF parsing is complex due to flexible encodings and stream formats allowed.",
  "PDF permissions are not cryptographically enforced and can be easily bypassed.",
  "PDF portfolios bundle multiple files with thumbnails into single container.",
  "PDF remained proprietary for 15 years before Adobe made it freely available.",
  "PDF signature subfilters support different cryptographic standards like PKCS#7.",
  "PDF specification allows custom security handlers for specialized encryption.",
  "PDF stands for Portable Document Format, designed to look same everywhere.",
  "PDF supports 3D content with U3D and PRC formats for CAD models since 1.6.",
  "PDF supports Unicode text since version 1.2 for multi-language documents.",
  "PDF supports advanced blend modes like multiply, screen, and overlay effects.",
  "PDF supports both AcroForms natively and XFA forms via XML Forms Architecture.",
  "PDF supports device-independent color spaces with ICC profiles for accuracy.",
  "PDF supports many compression filters: Flate, JPEG, JPEG2000, and JBIG2.",
  "PDF supports maximum page sizes up to 14400x14400 points or even larger.",
  "PDF supports multimedia like embedded audio, video, and Flash content.",
  "PDF supports spot colors and Pantone inks for precise printing requirements.",
  "PDF supports tiling patterns and gradient shading for advanced graphic fills.",
  "PDF tables are created by drawing lines and text, not as native table objects.",
  "PDF uses 40-bit to 256-bit encryption, with PDF 2.0 mandating AES-256.",
  "PDF uses stack-based graphics commands similar to PostScript for drawing.",
  "PDF viewers can reflow tagged PDFs into columns for easier mobile reading.",
  "PDF viewers progressively render pages showing coarse then refined detail.",
  "PDF viewers tolerate minor errors like missing endobj or duplicate keys gracefully.",
  "PDF was created by Adobe co-founder John Warnock in 1991 as the Camelot project.",
  "PDF.js is Mozilla's JavaScript library for rendering PDFs in web browsers.",
  "PDF/A is the archival standard requiring embedded fonts and no encryption.",
  "PDF/A-1 has two levels: 'a' for accessible with tagging, 'b' for basic viewing.",
  "PDF/A-2 and PDF/A-3 allow JPEG2000 compression unlike PDF/A-1 based on PDF 1.4.",
  "PDF/E supports engineering workflows with 3D CAD models and interactive diagrams.",
  "PDF/UA is the accessibility standard requiring proper tagging and alt text.",
  "PDF/X is for printing, requiring embedded fonts and CMYK or spot colors only.",
  "PDFs begin with %PDF-1.x magic number to identify the file type and version.",
  "Page rotation can be set per page, allowing mixed portrait and landscape.",
  "Page-level boundaries define MediaBox for full page and TrimBox for final size.",
  "Patterns and shadings were introduced in PDF 1.2 and 1.3 for advanced graphics.",
  "Printer marks like crop and registration marks were added in PDF 1.3 and 1.4.",
  "Redaction permanently removes content by overlaying and deleting underlying data.",
  "Rendering differences across viewers come from anti-aliasing and font handling.",
  "Reusable content like logos can be referenced multiple times to save file size.",
  "Reverse engineering PDFs is possible since specification is publicly available.",
  "Right-to-left scripts and vertical text are supported since PDF 1.3.",
  "Screen readers like JAWS and NVDA can read properly tagged PDFs in order.",
  "Scripted animation requires JavaScript changing content on timers, rarely used.",
  "Searchable PDFs require OCR to add invisible text layer over scanned images.",
  "Section 508 and EN 301 549 require accessible PDFs conforming to PDF/UA standard.",
  "Security scanners can inspect PDF content streams for suspicious malicious code.",
  "Signing PDFs uses X.509 certificates and standard cryptographic primitives.",
  "Standard MIME type for PDF is application/pdf for web and email transfers.",
  "Subsetting embeds only used font glyphs to reduce file size dramatically.",
  "Tagged PDF includes structure tags for accessibility and screen reader support.",
  "Tagged PDF marks table structures for accessibility even without table objects.",
  "Terminal tools like pdfinfo and pdftk can output PDF metadata as text dumps.",
  "The PDF magic number %PDF must be in the first line of every valid PDF file.",
  "The cross-reference table allows random access to any object without reading all.",
  "The first PDF version 1.0 and Acrobat software launched in January 1993.",
  "The largest PDF ever opened in Adobe Reader was an incredible 816,960 pages.",
  "There are 14 base fonts like Times and Helvetica that viewers substitute.",
  "Thumbnail previews can be embedded in PDFs or generated dynamically by viewers.",
  "ToUnicode mapping ensures copied text from PDF appears as correct characters.",
  "Usage rights signatures unlock features like form saving in free Adobe Reader.",
  "User passwords decrypt PDFs while owner passwords set print and copy permissions.",
  "Vector graphics in PDFs scale infinitely without quality loss when zooming.",
  "Windows 10+ includes Microsoft Print to PDF as a native built-in printer.",
  "Windows Explorer and macOS Finder show PDF thumbnails with preview handlers.",
  "ZUGFeRD combines PDF/A-3 with embedded XML for German e-invoice standard.",
  "macOS has Preview app built-in that can view, annotate, and merge PDFs easily.",
  "veraPDF is an open-source validator for checking PDF/A and PDF/UA conformance.",
];

export function getRandomFact(): string {
  return funFacts[Math.floor(Math.random() * funFacts.length)];
}
